### ISSUE TITLE
Power button & LED's

### ISSUE THREAD

**Issue by DigitalRoadi3s** [sgofferj/CM3588-NAS-case#4]
I printed this case via a 3rd party for $16, thanks for the files. I would suggest a V2 versions of this case that puts the fan's on the right side of the case where the CPU is so that the power button can be exposed. Also it would be nice to have an air slot up front to see the SSD LED's flashing.

Otherwise great design, thank you so much.

**Comment by eabase** [comment]
Yep, very strange design.
- the air slots should be on top, over the CPU.
- The fans on the side doesn't make sense, as you have the GPIO header there including 2 switches.

**Comment by sgofferj** [comment]
I don't use the GPIO header for anything but power for the fans. The airflow design is so that the fans pull the air over the CPU and the SSDs. Airflow from side to side is intentional because I have my case in a rack with stuff on top of it and below it.
If you need air holes on top, you can buy the official metal case from FriendlyElec.
